name: Feature Request
description: Suggest a new idea for this project
title: "<title>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Purpose
      description: What will this feature provide?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have an idea on how to implement this feature, please share!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Please list the requirements the implementation of this feature needs to meet.
      placeholder: |
        - This feature should do [xyz]
        - This feature should do [abc]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots here. 
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
